exempt-players:
  - 'example'

giveaway:
  countdown: 200 # time in ticks, 20 ticks in a second

enchant-map:
  arrow_damage: 'Power'
  arrow_fire: 'Flame'
  arrow_infinite: 'Infinity'
  arrow_knockback: 'Punch'
  binding_curse: 'Curse of Binding'
  channeling: 'Channeling'
  damage_all: 'Sharpness'
  damage_arthropods: 'Bane of Arthropods'
  damage_undead: 'Smite'
  depth_strider: 'Depth Strider'
  dig_speed: 'Efficiency'
  durability: 'Unbreaking'
  fire_aspect: 'Fire Aspect'
  frost_walker: 'Frost Walker'
  impaling: 'Impaling'
  knockback: 'Knockback'
  loot_bonus_blocks: 'Fortune'
  loot_bonus_mobs: 'Looting'
  loyalty: 'Loyalty'
  luck: 'Luck of The Sea'
  piercing: 'Piercing'
  protectional_environmental: 'Protection'
  protection_explosion: 'Explode Prot'
  protection_fire: 'Fire Protection'
  protection_projecticle: 'Projecticle Protection'
  quick_charge: 'Quick Charge'
  riptide: 'Riptide'
  silk_touch: 'Silk Touch'
  soul_speed: 'Soul Speed'
  sweeping_edge: 'Sweeping Edge'
  thorns: 'Thorns'
  vanishing_curse: 'Curse Of Vanishing'
  water_worker: 'Aqua Afinitity'